apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-e-m-backend
  labels:
    app: react-e-m-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-e-m-backend
  template:
    metadata:
      labels:
        app: react-e-m-backend
    spec:
      containers:
      - name: react-e-m-backend
        image: teperwoman/react-e-m-backend
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-e-m-frontend
  labels:
    app: react-e-m-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-e-m-frontend
  template:
    metadata:
      labels:
        app: react-e-m-frontend
    spec:
      containers:
      - name: react-e-m-frontend
        image: teperwoman/react-e-m-frontend
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: react-e-m-backend
spec:
  selector:
    app: react-e-m-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-e-m-frontend
spec:
  selector:
    app: react-e-m-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
