apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-e-m-frontend
  labels:
    app: react-e-m-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-e-m-frontend
  template:
    metadata:
      labels:
        app: react-e-m-frontend
    spec:
      containers:
      - name: react-e-m-frontend
        image: tftest/react-e-m-frontend
        ports:
        - containerPort: 3000
        
---

apiVersion: v1
kind: Service
metadata:
  name: react-e-m-frontend
spec:
  selector:
    app: react-e-m-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

