apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-e-m-backend
  labels:
    app: react-e-m-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-e-m-backend
  template:
    metadata:
      labels:
        app: react-e-m-backend
    spec:
      containers:
      - name: react-e-m-backend
        image: tftest/react-e-m-backend
        ports:
        - containerPort: 3000


---

apiVersion: v1
kind: Service
metadata:
  name: react-e-m-backend
spec:
  selector:
    app: react-e-m-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
